#/bin/sh

DOMAIN="tlp.digeiz.fr"
CONF_DIR="$HOME/.ssh/config.d"
HOSTS_FILE="hosts"

# Create ssh_config directory if it doesn't exist
mkdir -p $CONF_DIR || true

# Check if Teleport is connected then login if not
tsh status >/dev/null 2>&1
if [ $? == 1 ]; then
  echo "[WARNING] Teleport is not connected, logging in..."
  tsh login --proxy=$DOMAIN --user=$USER
fi

# tsh config
tsh config > "$CONF_DIR/teleport"
chmod 600 "$CONF_DIR/teleport"

# Generate hosts list from Teleport
HOSTS_LIST=$(tsh ls |awk '{print $1}' | tail -n +3 | grep -v ${DOMAIN} | sort)

echo "# Config generated by Teleport - Don't update this file manually" > "$CONF_DIR/$HOSTS_FILE"
chmod 600 $CONF_DIR/$HOSTS_FILE

cat << EOF >> "$CONF_DIR/$HOSTS_FILE"

Host *.$DOMAIN
  User root

EOF

for host in $HOSTS_LIST; do
  cat << EOF >> "$CONF_DIR/$HOSTS_FILE"
  Host $host
    HostName $host.$DOMAIN
EOF
done
