require("custom.configs.oilnvim")
require("custom.configs.filetypes")
require("custom.configs.vimopts")
require("custom.configs.harpoon")
require("custom.configs.gitworktree")
require("custom.configs.neogit")
