export CLICOLOR=1
export EDITOR="nvim"
# Allow zsh-autosuggestions to persist
setopt APPEND_HISTORY
setopt SHARE_HISTORY
HISTFILE=$HOME/.zsh_history
SAVEHIST=1000
HISTSIZE=999
setopt HIST_EXPIRE_DUPS_FIRST
setopt EXTENDED_HISTORY

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source <(fzf --zsh)

# zsh completion to correct approximations & give select menu for multiple choices
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select
zstyle ':completion:*' completer _extensions _complete _approximate

eval "$(starship init zsh)"

alias ls="eza"

. "$HOME/.atuin/bin/env"

eval "$(atuin init zsh)"
