-- vim.keymap.set('i', '<C-y>', function () return vim.fn['codeium#Accept']() end, { expr = true })
-- vim.keymap.set('i', '<C-;>', function() return vim.fn['codeium#CycleCompletions'](1) end, { expr = true })
-- vim.keymap.set('i', '<C-,>', function() return vim.fn['codeium#CycleCompletions'](-1) end, { expr = true })
-- vim.keymap.set('i', '<C-x>', function() return vim.fn['codeium#Clear']() end, { expr = true })
vim.keymap.set('n', '<leader>cs', '<CMD>Codeium Enable<CR>', { desc = "Enable Codeium" })
vim.keymap.set('n', '<leader>cd', '<CMD>Codeium Disable<CR>', { desc = "Disable Codeium" })
