local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Telescope find files"})
vim.keymap.set('n', '<leader>fw', builtin.live_grep, { desc = "Telescope live grep"})
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Telescope search buffers"})
vim.keymap.set('n', '<leader>fo', builtin.oldfiles, { desc = "Telescope Open old files"})
vim.keymap.set('n', '<leader>fz', builtin.current_buffer_fuzzy_find, { desc = "Telescope search current buffer"})
